### PR TITLE
camelize method now is static

### PR DESCRIPTION
**Pull request by AlessandroMinoccheri**
camelize method now is static to not instantiate every time the object

### CODE REVIEW

**Comment by AlessandroMinoccheri** [comment]
Yes sure, what do you think to transform all methods inside this class into static? But for a next release because is a breaking change for the actual code

**Comment by AlessandroMinoccheri** [comment]
Update code will all methods static for a future release

**Comment by sensorario** [comment]
Tests are green?

**Comment by AlessandroMinoccheri** [comment]
Yes tests are green, means that this bundle needs more tests

**Pull request closed without merging**
