### PR TITLE
add find all without pagination

### PR DESCRIPTION
**Pull request by gherry77**
| Q             | A
| ------------- | ---
| Branch?       | 2.4
| Minor version?      | (2.4)
| Hotfix?       | no  
| Refactoring?  | no 
| New feature?  | yes 
| BC breaks?    | no
| Deprecations? | no
| Tests pass?   | yes

# New Feature: Find All No Paginated

Added a new method in BaseRepository
When you need results applying filter and sort without pagination

`public function findAllNoPaginated();`

This feature was needed to create an Excel Report, injecting results into the Excel Report

### CODE REVIEW

**Comment by gherry77** [comment]
Yes it could. How do you suggest to create the test?

**Comment by AlessandroMinoccheri** [comment]
I think that a good way to make a test on that function to explicit the return format of the data, so you can view the difference between a data paginated (into another test that already exists) and this new feature

**Comment by AlessandroMinoccheri** [comment]
Another way instead of a test is to create a little piece of documentation inside README file where you explain the difference between findAllNoPaginated and findAllPaginated, more easy and fast to do I think @gherry77

**Comment by sensorario** [comment]
please update changelog

**Comment by AlessandroMinoccheri** [comment]
Not valid

**Pull request closed without merging**
